# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-redis
  template:
    metadata:
      labels:
        app: argocd-redis
    spec:
      containers:
      - name: redis
        image: redis:6.2
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-redis
spec:
  selector:
    app: argocd-redis
  ports:
    - port: 6379
---
# Argo CD server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-server
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      containers:
      - name: argocd-server
        image: quay.io/argoproj/argocd:v3.3.6
        ports:
        - containerPort: 8080
        env:
        - name: ARGOCD_REDIS
          value: "argocd-redis:6379"
        securityContext:
          runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
spec:
  selector:
    app: argocd-server
  ports:
    - port: 8080